version: '3.7'

services:
  publish-flotte-gbfs:
    image: ghcr.io/bbnavi/publish-flotte-gbfs
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:?missing env var MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:?missing env var MINIO_SECRET_KEY}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    networks:
      - public

networks:
  public:
    external: true
